name: Docker Image CI

on:
  push:
    branches: [ "php7-fpm" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag php7-fpm:$(date +%s)
